apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctsebackend01
  name: ctsebackend01
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctsebackend01
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctsebackend01
    spec:
      containers:
        # - image: it19062266/ctse_inventory:latest
        - image: it19062266/ctse_inventory:{{tag}}
          imagePullPolicy: Always
          name: ctse_inventory
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30