apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctsebackend01
  name: ctsebackend01
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: ctsebackend01
status:
  loadBalancer: {}